### ISSUE TITLE
Compatibility issues persist with os.execute

### ISSUE THREAD

**Issue by sy3c4ll** [ShamanBlobar/Connect-Four#1]
`sh: line 1: cls: command not found`

`os.execute(clearCommand)` still does not work for Unix.

**Comment by sy3c4ll** [comment]
`cls` on /bin/sh for Linux returns code 127, so presumably
`if not os.execute(clearCommand)`
on line 6 may not evaluate to true, hence
`clearCommand = "clear"`
on line 7 may not be executed for Unix systems.

**Comment by ShamanBlobar** [comment]
i fixed it try again
